[[constraint]]
  name = "github.com/parnurzeal/gorequest"
  version = "0.2.15"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/xmlpath.v2"

[prune]
  go-tests = true
  unused-packages = true
